### ISSUE TITLE
getting CORS errors when I test from my dev environment

### ISSUE THREAD

**Issue by raafirivero** [kevinn03/nba_api#5]
Hi Kevin. This looks super useful and I'd like to use this for a project I'm working on. (was thinking of building something similar, so thanks!).  Could you add * or localhost* to allowed origins on the heroku-hosted version? I can run it as a server on my dev environment with no issues, but as this API will likely exist as a module within a larger site I need to access this API via `fetch` and thus CORS issues when using front-end frameworks.

OR if it's bundled/exported as an NPM package then I could just run it via a function within my app. (using Svelte, btw). Psyched to test this out.

**Comment by kevinn03** [comment]
> Hi Kevin. This looks super useful and I'd like to use this for a project I'm working on. (was thinking of building something similar, so thanks!). Could you add * or localhost* to allowed origins on the heroku-hosted version? I can run it as a server on my dev environment with no issues, but as this API will likely exist as a module within a larger site I need to access this API via `fetch` and thus CORS issues when using front-end frameworks.
> 
> OR if it's bundled/exported as an NPM package then I could just run it via a function within my app. (using Svelte, btw). Psyched to test this out.

Hey raafirivero, I added cors to the app. It should work now.

**Comment by raafirivero** [comment]
Works like a charm - thanks!
