### ISSUE TITLE
Article Titles

### ISSUE THREAD

**Issue by raafirivero** [kevinn03/nba_api#6]
Got it working pretty nicely. Some of the titles come in clean, but for ones that are sourced from what seems like the article hash there are a couple issues. I wrote a little function that cleans the hyphens from between the words and capitalizes the words (except for prepositions). Pasting that below, or let me know if you'd like for me to submit it as a Pull request. 

The larger issue with those titles however is that they're like the SEO keywords and not the actual titles of the underlying articles. So, for instance, a title that comes through the API as `Raptors Trade Ben Simmons Domantas Sabonis` links to full article with the following title `Should Raptors trade for Ben Simmons, Domantas Sabonis? Case for and against potential major moves`. Attaching a couple screengrabs from my dev site and the final article. Haven't delved into how to fix that, but it should probably be addressed. Pasting my title cleaning function below:

> 
    function cleanTitle(title) {
        let cleaned = title.replace(/-/g, ' ');
        var textArray = cleaned.split(' ')
        var capitalizedText = ''
        let prepositions = [
            'a',
            'for',
            'in',
            'of',
            'on',
            'the', 
            'to', 
            'with'
        ];
        const nba = 'NBA';

        textArray.forEach((word, i) => {
            if (prepositions.includes(word)){
                // Don't capitalize prepositions...
                capitalizedText += word + ' ';

            } else {

                if (word.toUpperCase() == nba) {
                    // DO capitalize "NBA"
                    word = word.toUpperCase()
                    capitalizedText += word + ' '

                } else {
                    // Only capitalize first letter of everything else
                    capitalizedText += word.charAt(0).toUpperCase() + textArray[i].slice(1) + ' ';
                }
            }
        });

        return capitalizedText;
    }
> 
API outputs:
![screen 2022-01-10 at 1 26 32 PM](https://user-images.githubusercontent.com/6245124/148821954-75def0e3-8f79-4f48-94ae-45904913a518.jpg)
Actual article title:
![screen 2022-01-10 at 12 57 57 PM](https://user-images.githubusercontent.com/6245124/148821955-d767a835-3a29-4ffe-b633-eca0800b3abc.jpg)
Title cleaner in action, plus note on a baseball article coming through the API:
![api-notes](https://user-images.githubusercontent.com/6245124/148821952-5e880ba5-c502-40b8-bdbd-af5e5154ebcd.png)
And finally, the API in action with the title cleaner. (still didn't catch 'ACL', but it works well):
![screen 2022-01-10 at 1 57 50 PM](https://user-images.githubusercontent.com/6245124/148823489-fbba80f7-48de-4cda-a4fb-63ed7599527e.jpg)

**Comment by raafirivero** [comment]
Got it running on the live site I'm building here: [nbaboxscores.com](https://nbaboxscores.com/) - happy to hop in and work on some of this stuff as well. -R

**Comment by kevinn03** [comment]
> Got it running on the live site I'm building here: [nbaboxscores.com](https://nbaboxscores.com/) - happy to hop in and work on some of this stuff as well. -R

Hey raafirivero, I fixed the title for articles from nba.com. 
I think the baseball article issue from yahoo is because they put a baseball article in the nba section.
![nbayahoo](https://user-images.githubusercontent.com/31199764/148846392-ed2fa8f5-e486-45ac-a744-5cd15305396a.png)

Ben Rohrbach doesn't usually write mlb articles.

**Comment by raafirivero** [comment]
Ah gotcha. One more thing: is it possible to include nba.com and ca.nba.com as separate sources? (both can be listed as NBA under the source object, but it looks like they have different news departments and different articles on each site. More Raptors stuff (understandably) on the Canadian version of the site.

**Comment by kevinn03** [comment]
> Ah gotcha. One more thing: is it possible to include nba.com and ca.nba.com as separate sources? (both can be listed as NBA under the source object, but it looks like they have different news departments and different articles on each site. More Raptors stuff (understandably) on the Canadian version of the site.

Should be working now.

**Comment by raafirivero** [comment]
That's great to hear. Gonna close this issue. Great work on this plugin. Is there a full NBA site you're working on now?

**Comment by kevinn03** [comment]
> That's great to hear. Gonna close this issue. Great work on this plugin. Is there a full NBA site you're working on now?

No. I'm probably going to make a nba stats api in the future
